### ISSUE TITLE
TypeError: Cannot read property 'pinDialog' of undefined

### ISSUE THREAD

**Issue by namnd** [Paldom/PinDialog#5]
Hi, 
I am not sure if the code is out dated or something but this is the error i got even though i am sure i have added the plugin
TypeError: Cannot read property 'pinDialog' of undefined

$ ionic plugin list
com.ionic.keyboard 1.0.3 "Keyboard"
com.phonegap.plugins.facebookconnect 0.10.1 "Facebook Connect"
hu.dpal.phonegap.plugins.PinDialog 0.1.3 "PinDialog"
nl.x-services.plugins.socialsharing 4.3.11 "SocialSharing"
org.apache.cordova.camera 0.3.3 "Camera"
org.apache.cordova.console 0.2.11 "Console"
org.apache.cordova.contacts 0.2.14 "Contacts"
org.apache.cordova.device 0.2.12 "Device"
org.apache.cordova.dialogs 0.2.10 "Notification"
org.apache.cordova.file 1.3.1 "File"
org.apache.cordova.file-transfer 0.4.7 "File Transfer"
org.apache.cordova.geolocation 0.3.10 "Geolocation"
org.apache.cordova.inappbrowser 0.5.3 "InAppBrowser"
org.apache.cordova.media-capture 0.3.4 "Capture"
org.apache.cordova.statusbar 0.1.8 "StatusBar"

Thanks a lot

**Comment by Paldom** [comment]
@CoderEmb,
great, good to know that :)
